"""
CosyVoice Local Zero-Shot Inference Server
Listens on port 50000 to provide zero-shot voice cloning for Local AI Waifu.
"""

import os
import sys
import io
from pathlib import Path
from typing import Optional
from pydantic import BaseModel
from fastapi import FastAPI, HTTPException, Response
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

app = FastAPI(title="CosyVoice Zero-Shot Inference Server", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Global model handle
cosyvoice_model = None
model_load_error = None

def init_model():
    global cosyvoice_model, model_load_error
    try:
        repo_path = Path(__file__).parent / "CosyVoice"
        if repo_path.exists() and str(repo_path) not in sys.path:
            sys.path.insert(0, str(repo_path))
        matcha_path = repo_path / "third_party" / "Matcha-TTS"
        if matcha_path.exists() and str(matcha_path) not in sys.path:
            sys.path.insert(0, str(matcha_path))
        import torch
        from cosyvoice.cli.cosyvoice import CosyVoice, CosyVoice2
        model_dir = Path(__file__).parent / "pretrained_models" / "CosyVoice-300M"
        if not model_dir.exists():
            # Check for alternative model directories
            candidates = list((Path(__file__).parent / "pretrained_models").glob("*CosyVoice*"))
            if candidates:
                model_dir = candidates[0]

        if model_dir.exists():
            print(f"[CosyVoice Server] Loading model from {model_dir} on CUDA: {torch.cuda.is_available()}...")
            cosyvoice_model = CosyVoice(str(model_dir))
            print("[CosyVoice Server] Model successfully loaded and ready for zero-shot cloning.")
        else:
            model_load_error = f"Model weights not found in {model_dir}. Please run setup_cosyvoice.ps1."
            print(f"[CosyVoice Server] {model_load_error}")
    except Exception as e:
        model_load_error = str(e)
        print(f"[CosyVoice Server] Warning during initialization: {e}")


class ZeroShotRequest(BaseModel):
    tts_text: str
    prompt_text: Optional[str] = ""
    prompt_wav: str
    emotion: Optional[str] = "neutral"


@app.get("/health")
async def health():
    has_torch = False
    cuda_available = False
    try:
        import torch
        has_torch = True
        cuda_available = torch.cuda.is_available()
    except ImportError:
        pass

    return {
        "status": "online",
        "service": "cosyvoice",
        "has_torch": has_torch,
        "cuda_available": cuda_available,
        "model_loaded": cosyvoice_model is not None,
        "error": model_load_error,
    }


@app.post("/inference_zero_shot")
async def inference_zero_shot(req: ZeroShotRequest):
    """
    Executes zero-shot voice cloning using the provided reference wav audio.
    """
    global cosyvoice_model
    if not req.tts_text.strip():
        raise HTTPException(status_code=400, detail="Text is required")

    prompt_path = req.prompt_wav
    # CosyVoice requires prompt audio to be under 30 seconds (ideal: 5-15s)
    try:
        import soundfile as sf
        info = sf.info(prompt_path)
        if info.duration > 25.0:
            trimmed_name = f"trimmed_{Path(prompt_path).stem[:30]}.wav"
            trimmed_path = str(Path(prompt_path).parent / trimmed_name)
            if not os.path.exists(trimmed_path):
                data, sr = sf.read(prompt_path)
                sf.write(trimmed_path, data[:sr * 12], sr)
            prompt_path = trimmed_path
    except Exception as e:
        print(f"[CosyVoice Server] Notice during audio inspection: {e}")

    try:
        import torch
        import torchaudio

        # If prompt_text is provided, use zero-shot; otherwise cross_lingual voice cloning
        if req.prompt_text and req.prompt_text.strip():
            output_generator = cosyvoice_model.inference_zero_shot(
                req.tts_text,
                req.prompt_text.strip(),
                prompt_path,
                stream=False
            )
        else:
            output_generator = cosyvoice_model.inference_cross_lingual(
                req.tts_text,
                prompt_path,
                stream=False
            )

        # Collect audio tensor
        audio_chunks = []
        for chunk in output_generator:
            audio_chunks.append(chunk["tts_speech"])

        if not audio_chunks:
            raise HTTPException(status_code=500, detail="No audio was generated by CosyVoice.")

        full_speech = torch.concat(audio_chunks, dim=1)
        
        # Write to WAV buffer
        buf = io.BytesIO()
        torchaudio.save(buf, full_speech, cosyvoice_model.sample_rate, format="wav")
        wav_bytes = buf.getvalue()

        return Response(content=wav_bytes, media_type="audio/wav")

    except Exception as e:
        print(f"[CosyVoice Server] Inference error: {e}")
        raise HTTPException(status_code=500, detail=f"Synthesis error: {str(e)}")


if __name__ == "__main__":
    init_model()
    uvicorn.run(app, host="127.0.0.1", port=50000)
